blank_issues_enabled: false
contact_links:
  - name: ğŸ“– PureChat Documentation
    url: https://docs.purechat.cn
    about: åˆ›å»ºé—®é¢˜å‰è¯·å…ˆæŸ¥çœ‹æ–‡æ¡£ã€‚
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/Hyk260/PureChat/discussions
    about: è¯·åœ¨æ­¤æé—®å’Œå›ç­”é—®é¢˜ã€‚
  - name: ğŸ› Bug Reports
    url: https://github.com/Hyk260/PureChat/issues/new?template=bug_report.md
    about: æŠ¥å‘Š PureChat ä¸­çš„ bugã€‚
  - name: âœ¨ Feature Requests
    url: https://github.com/Hyk260/PureChat/issues/new?template=feature_request.md
    about: ä¸º PureChat å»ºè®®æ–°åŠŸèƒ½ã€‚
  - name: â“ Questions
    url: https://github.com/Hyk260/PureChat/issues/new?template=question.md
    about: è¯¢é—®å…³äº PureChat çš„é—®é¢˜ã€‚
  - name: ğŸ“š Documentation
    url: https://github.com/Hyk260/PureChat/issues/new?template=documentation.md
    about: å»ºè®®æ–‡æ¡£æ”¹è¿›ã€‚
  - name: âš¡ Performance Issues
    url: https://github.com/Hyk260/PureChat/issues/new?template=performance.md
    about: æŠ¥å‘Šæ€§èƒ½é—®é¢˜ã€‚ 